Fix configobj to relay tuple type errors
pazz/alot pull request #1633
Opened 2023-11-25 03:15 UTC by brandonpayton

Some current config tuple checking is of the form:

```python
if not isinstance(value[1], int) or not isinstance(value[2], int):
    VdtTypeError(value)
```

This has two problems. The first is that `isinstance('123', int)` is always `False`, which means the if's block always runs. A `VdtTypeError` would always be raised except that the `raise` keyword is missing.

This PR attempts to fix that issue.

2023-11-26 17:47 UTC, lucc commented
This `width_tuple` function looks quite simple. Do you mind adding some tests to `tests/utils/test_configobj.py`? Preferably also for the error handling that you improved (i.e. asserting that the right exceptions are thrown).

2023-11-27 03:42 UTC, brandonpayton commented
I committed some tests but need to break them into smaller pieces and add one or two more.

2023-11-27 03:43 UTC, brandonpayton commented
Thanks also for taking a look at this.

2023-11-27 05:07 UTC, lucc requested changes
The code itself looks good. I suggest breaking the test cases up into individual functions so that each function checks exactly "one thing".

2023-11-27 05:07 UTC, lucc commented on tests/utils/test_configobj.py
> +
```suggestion


class TestWidthTuple(unittest.TestCase):

```

2023-11-27 05:07 UTC, lucc commented on tests/utils/test_configobj.py
> +    def test_validates_width_tuple_for_fit(self):
```suggestion
    def test_validates_width_tuple_for_fit_requires_two_args(self):
```

2023-11-27 05:07 UTC, lucc commented on tests/utils/test_configobj.py
> +        with self.assertRaises(VdtValueError):
```suggestion

    def test_args_for_fit_must_be_numbers(self):
        with self.assertRaises(VdtValueError):
```

2023-11-27 05:07 UTC, lucc commented on tests/utils/test_configobj.py
> +        fit_result = checks.width_tuple(['fit', 123, 456])
```suggestion

    def test_fit_with_two_numbers(self):
        fit_result = checks.width_tuple(['fit', 123, 456])
```

2023-11-27 05:07 UTC, lucc commented on tests/utils/test_configobj.py
> +    def test_validates_width_tuple_for_weight(self):
```suggestion
    def test_validates_width_tuple_for_weight_needs_an_argument(self):
```

2023-11-27 05:07 UTC, lucc commented on tests/utils/test_configobj.py
> +        with self.assertRaises(VdtValueError):
```suggestion

    def test_arg_for_width_must_be_a_number(self):
        with self.assertRaises(VdtValueError):
```

2023-11-27 05:07 UTC, lucc commented on tests/utils/test_configobj.py
> +        weight_result = checks.width_tuple(['weight', 123])
```suggestion

    def test_width_with_a_number(self):
        weight_result = checks.width_tuple(['weight', 123])
```

2023-11-27 15:14 UTC, brandonpayton commented
That is much cleaner. Thank you!

2023-11-27 18:07 UTC, merged