make default theme readable
pazz/alot pull request #1640
Opened 2023-12-08 11:40 UTC by meeuw

Fixes #1639

2023-12-11 08:20 UTC, pazz requested changes
I do not mind changes to the default theme and if this improves visibility I'm happy with it. 
The theme tester script is a welcome addition!

My only two concerns before we can merge this are 
1) let's squash this into one commit or, even better, have one for the theme and one for the script.
2) please run a flake8 or some other python style checker on the script, so that we do not drop on silly code-quality measures
Thanks

2023-12-11 19:28 UTC, meeuw commented
Sure, no problem, squashed commits and I will move the Python script to another PR.

2023-12-12 09:46 UTC, pazz commented
thanks!

2023-12-12 09:48 UTC, pazz approved these changes

2023-12-12 09:51 UTC, merged